### ISSUE TITLE
How to run that dapp?

### ISSUE THREAD

**Issue by fuhailin** [nikhilvc1990/AgriChain#2]
Thanks for your kind sharing of this repo, I am just fresh to dapps development. I have configurated Truffle and Ethereum on my PC,  now I want to learn how to develop a dapp, could you please tell me how to run your AgroChain dapp on my local computer?
and I have a environment like this:
OS: Ubuntu 16.04 
node --version: v8.9.3
npm --version: 5.6.0
truffle version: Truffle v4.0.4 (core: 4.0.4)
Solidity v0.4.18 (solc-js)

**Comment by nikhilvc1990** [comment]
https://github.com/Kerala-Blockchain-Academy/AgroChain/blob/master/Important%20Instructions.txt
